### ISSUE TITLE
LAYABOX IDE 版本 2.12，分离模式，构建报错：layaMaxUI.TS error: Multiple exports with the same name "ui"

### ISSUE THREAD

**Issue by wangduoguo** [yayaluoya/layaBoxEsBuild#2]
![image](https://user-images.githubusercontent.com/5775182/117008431-4c424380-ad1d-11eb-91f7-17a2c942226b.png)

**Comment by yayaluoya** [comment]
能看下代码吗，可能是哪里语法有问题。

**Comment by yayaluoya** [comment]
我就遇到过
//报错
import Script3D = Laya.Script3D;
import Scene = Laya.Scene;
export module hhhhhhh {
    // export class _Script3D extends Script3D {
    // }
    export class _Scene extends Scene {
    }
}

//不报错
import Script3D = Laya.Script3D;
import Scene = Laya.Scene;
export module hhhhhhh {
    export class _Script3D extends Script3D {
    }
    export class _Scene extends Scene {
    }
}

**Comment by huugle** [comment]
有空引入,把没有用到的import 注释了就可以正常跑起来了.

**Comment by wangduoguo** [comment]
export class GameSceneUI extends Scene 改成 export class GameSceneUI extends Laya.Scene就行了
好像不能 import Scene = Laya.Scene;

**Comment by yayaluoya** [comment]
哈哈哈，有点玄乎，你们为什么还在用laya2.12哇，新版不爽吗

**Comment by yayaluoya** [comment]
这个问题我已经向esbuild提过了，他们好像已经修复了，等段时间我也同步一下，以后就不怕这个问题啦哈哈哈。
看这里 [esbuild新版本](https://github.com/evanw/esbuild/releases/tag/v0.11.21)

**Comment by yayaluoya** [comment]
更新好了，1.1.10 🌝

**Comment by wangduoguo** [comment]
升级了，可以正常使用，感谢
LAYA 2.12不是最新的版本吗？
