### ISSUE TITLE
执行脚本之后，asset下的资源都加载失败，去掉?version=1.0.0, 就可以访问到资源

### ISSUE THREAD

**Issue by raizo-coder** [yayaluoya/layaBoxEsBuild#4]
去掉?version=1.0.0之后就能加载到
![image](https://user-images.githubusercontent.com/54347262/120324889-b567a780-c319-11eb-8407-b89d69c52444.png)
加了?version=1.0.0 就读取不到， 啥原因
![image](https://user-images.githubusercontent.com/54347262/120324957-c87a7780-c319-11eb-8fe4-01c66f1b863a.png)

脚本：layabox-esbuild -c ./esbuildConfig.js

/** 配置数据 */
module.exports = {
    /** 代理src目录，可以是绝对路径或者相对路径 */
    src: './src/',
    /** 代理bin目录，可以是绝对路径或者相对路径 */
    bin: './bin/',
    /** 文件路径修改，会把 a 匹配的替换成 b */
    filePathModify: [
        {
            a: /^src\//,
            b: '/'
        }
    ],
    /** 代理端口，可以随便指定，为0则自动分配，只要不冲突就行 */
    port: {
        src: 0,
        bin: 0,
    },
    /** src目录文件默认后缀  */
    srcFileDefaultSuffix: 'ts',
    /** 入口文件名，地址相对于src目录 */
    mainTs: 'Main.ts',
    /** 主页， 相对于bin目录 */
    homePage: 'index.html',
    /** 主页脚本， 相对于bin目录 */
    homeJs: 'index.js',
    /** 入口js文件，相对于bin目录 */
    mainJs: 'js/bundle.js',
    /** 是否打印日志 */
    ifLog: false,
    /** 是否启用webSocket工具 */
    ifOpenWebSocketTool: true,
    /** 是否立即刷新浏览器 */
    ifUpdateNow: true,
};

**Comment by raizo-coder** [comment]
是在项目目录下执行的命名， 也就是src和bin所在的目录。
代码加载都没啥问题，资源加载全挂了
![image](https://user-images.githubusercontent.com/54347262/120326399-425f3080-c31b-11eb-914e-17d469b5870e.png)

**Comment by raizo-coder** [comment]
![image](https://user-images.githubusercontent.com/54347262/120479574-aac41580-c3e0-11eb-9c06-bc3b05a0a0dd.png)
打印信息看了下，原来是加载本地资源，绝对路径。难怪加缓存信息加载无效

**Comment by yayaluoya** [comment]
你为什么要加个?version=1.0.0呀，
我只是代理了bin目录，是不会处理请求参数的，而且我是直接读的请求地址，包括了后面的参数的，所以你请求不到，哈哈哈。
你不用自己创建一个配置文件，默认的因该就ok啦，而且有个快捷命令leb，在项目目录下执行leb就可以跑了，不用那么复杂，越简单越好。

**Comment by raizo-coder** [comment]
那是因为项目内网加载就是会用到?version = 1.0.0, 应该是版本管理，我在插件接受url的地方把这个拆分去掉了，配置文件还是要的，要是入口文件名修改了，确不知道怎么配置。多人合作项目，就应该细节点好。 谢谢

**Comment by yayaluoya** [comment]
Soga

**Comment by raizo-coder** [comment]
这个插件是不是只适用于laya2.0, 好像1.0都是零散的js文件，所以一直加载文件，打开链接非常慢。
![image](https://user-images.githubusercontent.com/54347262/120582697-7c394f80-c45f-11eb-95de-ade096fd6a5a.png)

**Comment by yayaluoya** [comment]
能跑起来吗？
是每次打开都很慢吗？

**Comment by yayaluoya** [comment]
应该只有第一次打开会比较慢，后续打开会经过缓存的，所以会比第一次打开快很多，而且建议用推荐的那个本地主页打开，这个地址访问会多一层缓存，又会快上不少。

**Comment by yayaluoya** [comment]
这个工具跟laya什么版本的没啥关系，只要是用js写的都行，不知道laya1.0有什么幺蛾子，我去试试看。

**Comment by yayaluoya** [comment]
> 这个工具跟laya什么版本的没啥关系，只要是用js写的都行，不知道laya1.0有什么幺蛾子，我去试试看。

1.0的官网都没有了。。。

**Comment by yayaluoya** [comment]
@raizo-coder 刚刚看了一下，确实不适合1.0，目录结构都变了。。。

**Comment by raizo-coder** [comment]
是的  加载一半，就跪了， 跑不起来

**Comment by yayaluoya** [comment]
其实也可以跑的
在bin目录下添加一个index.js文件，内容为
loadLib("js/bundle.js");
然后把index.html改一下，大概为
<!DOCTYPE html>
<html>

<head>
	<meta charset='utf-8' />
	<title>www.layabox.com</title>
	<meta name='viewport'
		content='width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no' />
	<meta name="renderer" content="webkit" />
	<meta name='apple-mobile-web-app-capable' content='yes' />
	<meta name='full-screen' content='true' />
	<meta name='x5-fullscreen' content='true' />
	<meta name='360-fullscreen' content='true' />
	<meta name="laya" screenorientation="landscape" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta http-equiv='expires' content='0' />
	<meta http-equiv="Cache-Control" content="no-siteapp" />
</head>

<body>
	<script type="text/javascript">
		function loadLib(url) {
			var script = document.createElement("script");
			script.async = false;
			script.src = url;
			document.body.appendChild(script);
		}
	</script>
	
	
	<script type="text/javascript" src="libs/laya.core.js"></script>
	
	<script type="text/javascript" src="libs/laya.wxmini.js"></script>
	
	<script type="text/javascript" src="libs/laya.bdmini.js"></script>
	
	<script type="text/javascript" src="libs/laya.xmmini.js"></script>
	
	<script type="text/javascript" src="libs/laya.quickgamemini.js"></script>
	
	<script type="text/javascript" src="libs/laya.bilimini.js"></script>
	
	<script type="text/javascript" src="libs/laya.Alipaymini.js"></script>
	
	<script type="text/javascript" src="libs/laya.qqmini.js"></script>
	
	<script type="text/javascript" src="libs/laya.ttmini.js"></script>
	
	<script type="text/javascript" src="libs/laya.hwmini.js"></script>
	
	<script type="text/javascript" src="libs/laya.tbmini.js"></script>
	
	<script type="text/javascript" src="libs/laya.webgl.js"></script>
	
	<script type="text/javascript" src="libs/laya.vvmini.js"></script>
	
	<script type="text/javascript" src="libs/laya.ani.js"></script>
	
	<script type="text/javascript" src="libs/laya.filter.js"></script>
	
	<script type="text/javascript" src="libs/laya.html.js"></script>
	
	<script type="text/javascript" src="libs/laya.particle.js"></script>
	
	<script type="text/javascript" src="libs/laya.tiledmap.js"></script>
	
	<script type="text/javascript" src="libs/laya.ui.js"></script>
	
	<script type="text/javascript" src="libs/laya.d3.js"></script>
	
	
	
	
	
	
	
	<script type="text/javascript" src="index.js"></script>
</body>

</html>
强行模仿2.0就能跑了，哈哈哈

**Comment by yayaluoya** [comment]
`
        
	<script type="text/javascript">
		function loadLib(url) {
			var script = document.createElement("script");
			script.async = false;
			script.src = url;
			document.body.appendChild(script);
		}
	</script>
	<script type="text/javascript" src="libs/laya.core.js"></script>
	
	<script type="text/javascript" src="index.js"></script>
`

**Comment by yayaluoya** [comment]
> 其实也可以跑的
> 在bin目录下添加一个index.js文件，内容为
> loadLib("js/bundle.js");
> 然后把index.html改一下，大概为
> 
> <title>www.layabox.com</title> <script type="text/javascript"> function loadLib(url) { var script = document.createElement("script"); script.async = false; script.src = url; document.body.appendChild(script); } </script> <script type="text/javascript" src="libs/laya.core.js"></script> <script type="text/javascript" src="libs/laya.wxmini.js"></script> <script type="text/javascript" src="libs/laya.bdmini.js"></script> <script type="text/javascript" src="libs/laya.xmmini.js"></script> <script type="text/javascript" src="libs/laya.quickgamemini.js"></script> <script type="text/javascript" src="libs/laya.bilimini.js"></script> <script type="text/javascript" src="libs/laya.Alipaymini.js"></script> <script type="text/javascript" src="libs/laya.qqmini.js"></script> <script type="text/javascript" src="libs/laya.ttmini.js"></script> <script type="text/javascript" src="libs/laya.hwmini.js"></script> <script type="text/javascript" src="libs/laya.tbmini.js"></script> <script type="text/javascript" src="libs/laya.webgl.js"></script> <script type="text/javascript" src="libs/laya.vvmini.js"></script> <script type="text/javascript" src="libs/laya.ani.js"></script> <script type="text/javascript" src="libs/laya.filter.js"></script> <script type="text/javascript" src="libs/laya.html.js"></script> <script type="text/javascript" src="libs/laya.particle.js"></script> <script type="text/javascript" src="libs/laya.tiledmap.js"></script> <script type="text/javascript" src="libs/laya.ui.js"></script> <script type="text/javascript" src="libs/laya.d3.js"></script> <script type="text/javascript" src="index.js"></script> 强行模仿2.0就能跑了，哈哈哈

就加个方法，引入index.js就行了

**Comment by raizo-coder** [comment]
我试试  谢谢

**Comment by raizo-coder** [comment]
index2.html ：
 <script type="text/javascript">
        function loadLib(url) {
			console.log("start raizo111");
            var script = document.createElement("script");
            script.async = false;
            script.src = url;
            document.body.appendChild(script);
        }
    </script>

	
	
	
	
	<script type="text/javascript" src="index.js"></script>
	
	

index.js：
	loadLib("js/game/uiext/a.js");
	loadLib("js/game/uiext/b.js");
	loadLib("js/game/uiext/v.js");
	loadLib("js/game/uiext/c.js");
	loadLib("js/game/virtualkeyboard/d.js");

1.0 不会编译生成一个bundle.js,  js文件夹下是所有的零散js单文件，一访问主页加载所有的单个js， 就扛不住了

**Comment by raizo-coder** [comment]
1.0 如果你测试可以的话  发个demo给我参考下

**Comment by yayaluoya** [comment]
好的，
https://gitee.com/yayaluoya/layabox1.0.git

**Comment by yayaluoya** [comment]
有一点需要注意，这个工具是不编译项目的，它不会对项目造成影响哦，它只是帮助开发，不参与打包。

**Comment by yayaluoya** [comment]
@raizo-coder 可以了吗？

**Comment by raizo-coder** [comment]
晚点我整理个 1.0的demo问题版本 git地址给你  看看是啥原因  
首先你给的git demo 确实没问题

**Comment by yayaluoya** [comment]
好的

**Comment by raizo-coder** [comment]
问题：1.0原来的加载顺序是  加载完  GameCfg.js  最后才是加载main.js， 它就编译的了。
换成 index.js 就会报 GameCfg 为空
类展示如下---
--
index.html:
<script type="text/javascript">
        function loadLib(url) {
            var script = document.createElement("script");
            script.async = false;
            script.src = url;
            document.body.appendChild(script);
        }
    </script>

	<script type="text/javascript" src="index.js"></script>
--
index.js:

loadLib("js/bundle.js");

--
main.ts：
module game {

    export class Main {

        constructor() {
            console.log(GameCfg.SPLASH);//编译报错  GameCfg为空
            console.log("raizo");
            console.log("raizo");
            console.log("raizo");
            console.log("raizo");
            console.log("raizo2");
        }
    }
}
new game.Main();
---
GameCfg.ts 
module game
{

   export class GameCfg
   {

        public static SPLASH: number = 0;
    }
}

**Comment by yayaluoya** [comment]
不是很懂，要不你建个仓库，把你的逻辑代码删了只保留报错的那部分，然后我拉下来跑下。

**Comment by raizo-coder** [comment]
https://gitee.com/raizo-cc/demo.git

**Comment by yayaluoya** [comment]
> https://gitee.com/raizo-cc/demo.git

可以正常跑呀

![捕获](https://user-images.githubusercontent.com/51780237/120660585-0f06d800-c4ba-11eb-831d-9ffc0cf4ebaf.JPG)

**Comment by yayaluoya** [comment]
我好像明白你的意思了，今天还有一个人遇到了这个问题，其实就是没导出的问题。
![捕获2](https://user-images.githubusercontent.com/51780237/120661437-d87d8d00-c4ba-11eb-894d-b9ff0b8c6200.JPG)
![捕获3](https://user-images.githubusercontent.com/51780237/120661446-dadfe700-c4ba-11eb-9bf5-2e746a1ab5cb.JPG)
具体原因是layaAir不管三七二十一把所有的文件都打包到了最终包中，因为它用的很老套的编译工具，不会按需编译，所以这样写是不规范的，最好不要怎么写。

**Comment by yayaluoya** [comment]
不要把这些东西写成全局的，造成污染不说，其实也是很不规范的，用就导入，不用就不导入，这样多好理解。
实在是全局的东西就写成生命文件通过其它方式引入不久行了。laya的那些库就是这么搞得呀，用js写的代码，然后通过ts写个外壳。

**Comment by yayaluoya** [comment]
这样写能跑完全是layaair的编译为了省事造成的漏洞，可千万别以为怎么写是对的啊。兄弟。

**Comment by raizo-coder** [comment]
这样写确实暴露在全局，正常的使用确实是应该import对应的模块，但是比较尴尬的问题是，一个项目已经成型了，几千个js文件，再改已经无能为力了。
有个疑问：同个模块，我定义了两个类，拆分为不同的类文件，不知道怎么import了。放到一个类文件里头就处理的了，但又不能全部都放到一个类文件里头。
同一个类文件 game2 module，可以访问 GameCfg2.SPLASH
![image](https://user-images.githubusercontent.com/54347262/120733861-7eacaf80-c51a-11eb-9783-f002b4fa53ec.png)
拆分为两个不同类文件，就不知道怎么访问 GameCfg2.SPLASH 的值了
![image](https://user-images.githubusercontent.com/54347262/120733955-a734a980-c51a-11eb-9f4e-c06628bbfbb7.png)

**Comment by yayaluoya** [comment]
这样就可以了
![捕获](https://user-images.githubusercontent.com/51780237/120735678-9f2a3900-c51d-11eb-8f3f-921dc6540548.PNG)
话说你为什么要包在module里面呢，特殊情况采用module，况且还有个namespace呢？
建议直接导出类，整那么麻烦干啥呢

**Comment by raizo-coder** [comment]
module或者namespace 能用一个还是要用一个，不然游戏分包就麻烦了。
现在的公司的游戏框架已经这样写了，没办法再动了。
谢谢解答  辛苦了

**Comment by yayaluoya** [comment]
分包还要分逻辑？这么复杂
几千个ts文件随便改点代码layaair不得编译一年，难怪你不怕麻烦来用这个工具。
