### ISSUE TITLE
.

### ISSUE THREAD

**Issue by liylho** [yayaluoya/layaBoxEsBuild#7]

**Comment by liylho** [comment]
log卡在这
![image](https://user-images.githubusercontent.com/44609402/124710442-5c4ded80-df2f-11eb-97e9-f935fb06e9e9.png)

页面这边是空白
![image](https://user-images.githubusercontent.com/44609402/124710508-78ea2580-df2f-11eb-8112-4b31672ddfb2.png)

node版本12.22.3

**Comment by liylho** [comment]
@yayaluoya

**Comment by yayaluoya** [comment]
你改了配置吗？

**Comment by liylho** [comment]
配置如下：

`"use strict";
function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }
/**
 * 文件监听类
 */
class FileWatch {
    /**
     * 初始化
     * @param {boolean} _enable 是否启用 [true]
     * @param {boolean} _usePolling 是否使用轮询，使用轮询的话可能会导致cpu占用过高，不使用轮询的话可能会导致文件夹占用不能删除 [true]
     * @param {number} _interval 轮询间隔时间，_usePolling=true时有效 [100]
     */
    constructor(_enable = null, _usePolling = null, _interval = null) {
        _defineProperty(this, "enable", true);

        _defineProperty(this, "usePolling", true);

        _defineProperty(this, "interval", 100);

        this.enable = _enable !== null && _enable !== void 0 ? _enable : this.enable;
        this.usePolling = _usePolling !== null && _usePolling !== void 0 ? _usePolling : this.usePolling;
        this.interval = _interval !== null && _interval !== void 0 ? _interval : this.interval;
    }
}
/** 
 * 配置数据
 */
module.exports = {
    /** 代理src目录，可以是绝对路径或者相对路径 */
    src: './src/',
    /** 代理bin目录，可以是绝对路径或者相对路径 */
    bin: './bin/',
    /** 文件路径修改，会把 a 匹配的替换成 b */
    filePathModify: [
        {
            a: /^src\//,
            b: '/'
        }
    ],
    /** 代理端口，可以随便指定，为0则自动分配，只要不冲突就行 */
    port: {
        src: 0,
        bin: 0,
    },
    /** src目录文件默认后缀  */
    srcFileDefaultSuffix: 'ts',
    /** 入口文件名，地址相对于src目录 */
    mainTs: 'GameMain.ts',
    /** 主页， 相对于bin目录 */
    homePage: 'index.html',
    /** 主页脚本， 相对于bin目录 */
    homeJs: 'index.js',
    /** 入口js文件，相对于bin目录 */
    mainJs: 'js/bundle.js',
    /** 自动更新任务时间，分 */
    autoUpdateTaskTime: 3,
    /** 是否打印日志 */
    ifLog: false,
    /** 是否启用webSocket工具 */
    ifOpenWebSocketTool: true,
    /** 是否立即刷新浏览器 */
    ifUpdateNow: true,
    /** 文件监听 */
    fileWatch: {
        /** src目录的监听配置，enable选项无效 */
        src: new FileWatch(),
        /** bin目录的监听配置 */
        bin: new FileWatch(true, true, 500),
    },
};`

**Comment by yayaluoya** [comment]
你改了什么呢？

**Comment by liylho** [comment]
> 你改了什么呢？

只有入口文件名

**Comment by yayaluoya** [comment]
你把这个设置为true看看终端会打印些什么东西呢
/* 是否打印日志 /
ifLog: false,

**Comment by liylho** [comment]
都是创建模块的log
![image](https://user-images.githubusercontent.com/44609402/124711690-f82c2900-df30-11eb-8244-05a2fef1c7cf.png)


> 你把这个设置为true看看终端会打印些什么东西呢
> /* 是否打印日志 /
> ifLog: false,

**Comment by liylho** [comment]
> 你把这个设置为true看看终端会打印些什么东西呢
> /* 是否打印日志 /
> ifLog: false,

都是创建模块的log
![image](https://user-images.githubusercontent.com/44609402/124711841-20b42300-df31-11eb-9abb-425a2d4a1198.png)

**Comment by yayaluoya** [comment]
那没问题呀，你看看浏览器都报了啥错误呢？

**Comment by liylho** [comment]
> 那没问题呀，你看看浏览器都报了啥错误呢？
![image](https://user-images.githubusercontent.com/44609402/124716460-ae464180-df36-11eb-9c35-c325d04b1965.png)

跨域请求问题

**Comment by yayaluoya** [comment]
是哪里的代码报的这个错呢？或者说是哪个请求跨域了，你截个大点的图

**Comment by liylho** [comment]
> 是哪里的代码报的这个错呢？或者说是哪个请求跨域了，你截个大点的图
就是一个普通的xhr请求，马赛克的就是地址

**Comment by yayaluoya** [comment]
是不是第地址填错了，我后端设置全跨域的

**Comment by liylho** [comment]
> 是不是第地址填错了，我后端设置全跨域的

地址没问题，我使用自己的构建工具都是完全正常的

**Comment by yayaluoya** [comment]
能给我看看吗？

**Comment by liylho** [comment]
> 能给我看看吗？
我看问题列表里，之前也有人有同样的问题。我先找下解决方案，稍后反馈给你。

**Comment by yayaluoya** [comment]
跨域的问题好像没有哦，你先找找吧

**Comment by liylho** [comment]
> 跨域的问题好像没有哦，你先找找吧
laya论坛上的一个反馈
![image](https://user-images.githubusercontent.com/44609402/124722677-da64c100-df3c-11eb-9bd3-bbc91002f227.png)

**Comment by yayaluoya** [comment]
报错接口的源是？

**Comment by yayaluoya** [comment]
你看下报错接口的响应头是不是这
![捕获32](https://user-images.githubusercontent.com/51780237/124726494-64625900-df40-11eb-8d86-b955b5c6a511.JPG)
样？

**Comment by liylho** [comment]
> 你看下报错接口的响应头是不是这
> ![捕获32](https://user-images.githubusercontent.com/51780237/124726494-64625900-df40-11eb-8d86-b955b5c6a511.JPG)
> 样？
request：
![image](https://user-images.githubusercontent.com/44609402/124727099-fa967f00-df40-11eb-956e-b13d247bf0b6.png)

response data load failed

**Comment by yayaluoya** [comment]
所以你还是给我看看接口是啥吧，你啥也不给看怎么找错误。。。

**Comment by liylho** [comment]
> 所以你还是给我看看接口是啥吧，你啥也不给看怎么找错误。。。

看下邮箱

**Comment by laimumu** [comment]
解决了吗 我这边用的时候也是空白界面

**Comment by yayaluoya** [comment]
> 解决了吗 我这边用的时候也是空白界面

你终端报啥错误没？

**Comment by laimumu** [comment]
![image](https://user-images.githubusercontent.com/18816260/134793841-89525f52-f70f-4f7a-b2f6-36959edfa57b.png)

**Comment by yayaluoya** [comment]
没问题呀

**Comment by laimumu** [comment]
> 没问题呀

但是画面是空白的，控制台也没什么提示

**Comment by yayaluoya** [comment]
你改了bin/index.js 和 bin/index.html 文件没？

**Comment by laimumu** [comment]
> 你改了bin/index.js 和 bin/index.html 文件没？

没改，新项目没问题，旧项目不行，旧项目用的laya版本比较老了

**Comment by yayaluoya** [comment]
旧项目bin/index.js和bin/index.html文件结构不同，就不行，你要改下才行
